version: "3" # if no version is specified then v1 is assumed. Recommend v2 minimum

services: # containers. same as docker run
  hmi-fe-framework:
    platform: linux/x86_64
    image: siliconlife/hmi-fe-framework
    container_name: hmi-fe-framework
    build: .
    restart: unless-stopped
    ports:
      - "6029:80"
    volumes:
      - ./fe_config.js:/usr/share/nginx/html/config.js